services:
  inventory_django:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: inventory_django
    # command: python manage.py runserver 0.0.0.0:8000
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
      - static_volume:/usr/src/app/static
      - media_volume:/usr/src/app/media
    ports:
      - "8001:8000"
    depends_on:
      - inventory_db

  
  inventory_db:
    image: postgres:15-alpine
    container_name: inventory_db
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5454:5432"
  
  nginx:
    image: nginx:1.21-alpine
    ports:
      - "80:80"
    volumes:
      - static_volume:/usr/src/app/static
      - media_volume:/usr/src/app/media
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - inventory_django


volumes:
  postgres_data:
  static_volume:
  media_volume: